version: '3.8'

services:

  ####### remove comment when needed (or if u want to test frontend in docker) #########
  react-nginx:
    build: ./frontend
    ports: 
      - "80:80"
    networks:
      - my-network

  taobin-express:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - sql
    environment:
      MYSQL_HOST: sql
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
    networks:
      - my-network

  sql:
    build: ./database
    container_name: sql
    volumes:
      - ./database/mysql-data:/var/lib/mysql
    ports:
      - "3307:3307"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge