version: '3.8'

services:
  taobin-express:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - sql
    environment:
      MYSQL_HOST: sql
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
    networks:
      - my-network

  sql:
    build: ./database
    container_name: sql
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3307"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge